stages:
    - build

build:
    stage: build
    tags:
        - ucs-build
    only:
        refs:
            - /^[1-9][0-9]*\.[0-9]+-[0-9]+$/    # Only build packages automatically for the main UCS branches
        changes:
            - "*/*/debian/changelog"
    script:
        - ./.build_unbuilt_packages
